//! 命令表的**唯一真源**。
//!
//! 桌面 (`tauri::Builder::invoke_handler`) 与 Android sidecar (`rpc::Handlers`)
//! 必须注册完全相同的 292 条命令，否则前端在两端行为不一致。
//! 这里用一个 `macro_rules!` 把列表抽出来，两边各展开一次。
//!
//! 注意：
//!   - 列表内的路径统一加 `crate::` 前缀（上游是 `commands::xxx` 相对路径 +
//!     裸 `update_tray_menu`），因为宏体会在 `lib.rs`（crate 根）和
//!     `sidecar.rs`（子模块）两处展开，相对路径在后者无法解析。
//!     `macro_rules!` 里的 `crate::` 在展开处解析，两个调用点同属本 crate。
//!   - `tauri::generate_handler!` 在桌面是真实宏、在 Android 是
//!     `tauri-shim-macros` 的同名宏（展开为 `Vec<(&str, HandlerFn)>`），
//!     签名差异由各自的宏负责，本文件不感知平台。

/// 展开为 `tauri::generate_handler![..]`。
///
/// 可在本 crate 任意模块内调用（路径已带 `crate::` 前缀）。
#[macro_export]
macro_rules! cc_switch_generate_handler {
    () => {
        tauri::generate_handler![
            crate::commands::get_providers,
            crate::commands::get_current_provider,
            crate::commands::add_provider,
            crate::commands::update_provider,
            crate::commands::delete_provider,
            crate::commands::remove_provider_from_live_config,
            crate::commands::switch_provider,
            crate::commands::import_default_config,
            crate::commands::get_claude_desktop_status,
            crate::commands::get_claude_desktop_default_routes,
            crate::commands::import_claude_desktop_providers_from_claude,
            crate::commands::ensure_claude_desktop_official_provider,
            crate::commands::ensure_codex_official_provider,
            crate::commands::ensure_grokbuild_official_provider,
            crate::commands::get_claude_config_status,
            crate::commands::get_config_status,
            crate::commands::get_claude_code_config_path,
            crate::commands::get_config_dir,
            crate::commands::open_config_folder,
            crate::commands::pick_directory,
            crate::commands::open_external,
            crate::commands::get_init_error,
            crate::commands::get_migration_result,
            crate::commands::get_skills_migration_result,
            crate::commands::get_app_config_path,
            crate::commands::open_app_config_folder,
            crate::commands::get_claude_common_config_snippet,
            crate::commands::set_claude_common_config_snippet,
            crate::commands::get_common_config_snippet,
            crate::commands::set_common_config_snippet,
            crate::commands::update_toml_common_config_snippet,
            crate::commands::extract_common_config_snippet,
            crate::commands::read_live_provider_settings,
            crate::commands::get_settings,
            crate::commands::save_settings,
            crate::commands::has_codex_unify_history_backup,
            crate::commands::restore_codex_unified_history,
            crate::commands::get_rectifier_config,
            crate::commands::set_rectifier_config,
            crate::commands::get_optimizer_config,
            crate::commands::set_optimizer_config,
            crate::commands::get_copilot_optimizer_config,
            crate::commands::set_copilot_optimizer_config,
            crate::commands::get_log_config,
            crate::commands::set_log_config,
            crate::commands::restart_app,
            crate::commands::install_update_and_restart,
            crate::commands::check_app_update_available,
            crate::commands::check_for_updates,
            crate::commands::is_portable_mode,
            crate::commands::copy_text_to_clipboard,
            crate::commands::get_claude_plugin_status,
            crate::commands::read_claude_plugin_config,
            crate::commands::apply_claude_plugin_config,
            crate::commands::is_claude_plugin_applied,
            crate::commands::apply_claude_onboarding_skip,
            crate::commands::clear_claude_onboarding_skip,
            // Claude MCP management
            crate::commands::get_claude_mcp_status,
            crate::commands::read_claude_mcp_config,
            crate::commands::upsert_claude_mcp_server,
            crate::commands::delete_claude_mcp_server,
            crate::commands::validate_mcp_command,
            // usage query
            crate::commands::queryProviderUsage,
            crate::commands::testUsageScript,
            // subscription quota
            crate::commands::get_subscription_quota,
            crate::commands::get_codex_oauth_quota,
            crate::commands::get_codex_oauth_models,
            crate::commands::get_xai_oauth_models,
            crate::commands::get_xai_oauth_quota,
            crate::commands::get_coding_plan_quota,
            crate::commands::get_balance,
            // New MCP via config.json (SSOT)
            crate::commands::get_mcp_config,
            crate::commands::upsert_mcp_server_in_config,
            crate::commands::delete_mcp_server_in_config,
            crate::commands::set_mcp_enabled,
            // Unified MCP management
            crate::commands::get_mcp_servers,
            crate::commands::upsert_mcp_server,
            crate::commands::delete_mcp_server,
            crate::commands::toggle_mcp_app,
            crate::commands::import_mcp_from_apps,
            // Prompt management
            crate::commands::get_prompts,
            crate::commands::upsert_prompt,
            crate::commands::delete_prompt,
            crate::commands::enable_prompt,
            crate::commands::import_prompt_from_file,
            crate::commands::get_current_prompt_file_content,
            // Profile management (项目配置方案)
            crate::commands::list_profiles,
            crate::commands::create_profile,
            crate::commands::update_profile,
            crate::commands::delete_profile,
            crate::commands::clear_current_profile,
            crate::commands::apply_profile,
            // model list fetch (OpenAI-compatible /v1/models)
            crate::commands::fetch_models_for_config,
            // ours: endpoint speed test + custom endpoint management
            crate::commands::test_api_endpoints,
            crate::commands::get_custom_endpoints,
            crate::commands::add_custom_endpoint,
            crate::commands::remove_custom_endpoint,
            crate::commands::update_endpoint_last_used,
            // app_config_dir override via Store
            crate::commands::get_app_config_dir_override,
            crate::commands::set_app_config_dir_override,
            // provider sort order management
            crate::commands::update_providers_sort_order,
            // theirs: config import/export and dialogs
            crate::commands::export_config_to_file,
            crate::commands::import_config_from_file,
            crate::commands::webdav_test_connection,
            crate::commands::webdav_sync_upload,
            crate::commands::webdav_sync_download,
            crate::commands::webdav_sync_save_settings,
            crate::commands::webdav_sync_fetch_remote_info,
            crate::commands::s3_test_connection,
            crate::commands::s3_sync_upload,
            crate::commands::s3_sync_download,
            crate::commands::s3_sync_save_settings,
            crate::commands::s3_sync_fetch_remote_info,
            crate::commands::save_file_dialog,
            crate::commands::open_file_dialog,
            crate::commands::open_zip_file_dialog,
            crate::commands::create_db_backup,
            crate::commands::list_db_backups,
            crate::commands::restore_db_backup,
            crate::commands::rename_db_backup,
            crate::commands::delete_db_backup,
            crate::commands::sync_current_providers_live,
            // Deep link import
            crate::commands::parse_deeplink,
            crate::commands::merge_deeplink_config,
            crate::commands::import_from_deeplink,
            crate::commands::import_from_deeplink_unified,
            crate::update_tray_menu,
            // Environment variable management
            crate::commands::check_env_conflicts,
            crate::commands::delete_env_vars,
            crate::commands::restore_env_backup,
            // Skill management (v3.10.0+ unified)
            crate::commands::get_installed_skills,
            crate::commands::get_skill_backups,
            crate::commands::delete_skill_backup,
            crate::commands::install_skill_unified,
            crate::commands::uninstall_skill_unified,
            crate::commands::restore_skill_backup,
            crate::commands::toggle_skill_app,
            crate::commands::scan_unmanaged_skills,
            crate::commands::import_skills_from_apps,
            crate::commands::discover_available_skills,
            crate::commands::check_skill_updates,
            crate::commands::update_skill,
            crate::commands::migrate_skill_storage,
            crate::commands::search_skills_sh,
            // Skill management (legacy API compatibility)
            crate::commands::get_skills,
            crate::commands::get_skills_for_app,
            crate::commands::install_skill,
            crate::commands::install_skill_for_app,
            crate::commands::uninstall_skill,
            crate::commands::uninstall_skill_for_app,
            crate::commands::get_skill_repos,
            crate::commands::add_skill_repo,
            crate::commands::remove_skill_repo,
            crate::commands::install_skills_from_zip,
            // Auto launch
            crate::commands::set_auto_launch,
            crate::commands::get_auto_launch_status,
            // Proxy server management
            crate::commands::start_proxy_server,
            crate::commands::stop_proxy_server,
            crate::commands::stop_proxy_with_restore,
            crate::commands::get_proxy_takeover_status,
            crate::commands::set_proxy_takeover_for_app,
            crate::commands::get_proxy_status,
            crate::commands::get_proxy_config,
            crate::commands::update_proxy_config,
            // Global & Per-App Config
            crate::commands::get_global_proxy_config,
            crate::commands::update_global_proxy_config,
            crate::commands::get_proxy_config_for_app,
            crate::commands::update_proxy_config_for_app,
            crate::commands::get_default_cost_multiplier,
            crate::commands::set_default_cost_multiplier,
            crate::commands::get_pricing_model_source,
            crate::commands::set_pricing_model_source,
            crate::commands::is_proxy_running,
            crate::commands::is_live_takeover_active,
            crate::commands::switch_proxy_provider,
            // Proxy failover commands
            crate::commands::get_provider_health,
            crate::commands::reset_circuit_breaker,
            crate::commands::get_circuit_breaker_config,
            crate::commands::update_circuit_breaker_config,
            crate::commands::get_circuit_breaker_stats,
            // Failover queue management
            crate::commands::get_failover_queue,
            crate::commands::get_available_providers_for_failover,
            crate::commands::add_to_failover_queue,
            crate::commands::remove_from_failover_queue,
            crate::commands::get_auto_failover_enabled,
            crate::commands::set_auto_failover_enabled,
            // Usage statistics
            crate::commands::get_usage_summary,
            crate::commands::get_usage_summary_by_app,
            crate::commands::get_usage_trends,
            crate::commands::get_provider_stats,
            crate::commands::get_model_stats,
            crate::commands::get_request_logs,
            crate::commands::get_request_detail,
            crate::commands::get_model_pricing,
            crate::commands::update_model_pricing,
            crate::commands::update_model_pricing_batch,
            crate::commands::delete_model_pricing,
            crate::commands::get_models_dev_sync_config,
            crate::commands::save_models_dev_sync_config,
            crate::commands::record_models_dev_sync_result,
            crate::commands::check_provider_limits,
            // Session usage sync
            crate::commands::sync_session_usage,
            crate::commands::rebuild_codex_usage,
            crate::commands::get_usage_data_sources,
            // Stream health check
            crate::commands::stream_check_provider,
            crate::commands::stream_check_all_providers,
            crate::commands::get_stream_check_config,
            crate::commands::save_stream_check_config,
            // Session manager
            crate::commands::list_sessions,
            crate::commands::get_session_messages,
            crate::commands::delete_session,
            crate::commands::delete_sessions,
            crate::commands::launch_session_terminal,
            crate::commands::get_tool_versions,
            crate::commands::run_tool_lifecycle_action,
            crate::commands::probe_tool_installations,
            // Provider terminal
            crate::commands::open_provider_terminal,
            // Universal Provider management
            crate::commands::get_universal_providers,
            crate::commands::get_universal_provider,
            crate::commands::upsert_universal_provider,
            crate::commands::delete_universal_provider,
            crate::commands::sync_universal_provider,
            // OpenCode specific
            crate::commands::import_opencode_providers_from_live,
            crate::commands::get_opencode_live_provider_ids,
            // OpenClaw specific
            crate::commands::import_openclaw_providers_from_live,
            crate::commands::get_openclaw_live_provider_ids,
            crate::commands::get_openclaw_live_provider,
            crate::commands::scan_openclaw_config_health,
            crate::commands::get_openclaw_default_model,
            crate::commands::set_openclaw_default_model,
            crate::commands::get_openclaw_model_catalog,
            crate::commands::set_openclaw_model_catalog,
            crate::commands::get_openclaw_agents_defaults,
            crate::commands::set_openclaw_agents_defaults,
            crate::commands::get_openclaw_env,
            crate::commands::set_openclaw_env,
            crate::commands::get_openclaw_tools,
            crate::commands::set_openclaw_tools,
            // Hermes specific
            crate::commands::import_hermes_providers_from_live,
            crate::commands::get_hermes_live_provider_ids,
            crate::commands::get_hermes_live_provider,
            crate::commands::get_hermes_model_config,
            crate::commands::open_hermes_web_ui,
            crate::commands::launch_hermes_dashboard,
            crate::commands::get_hermes_memory,
            crate::commands::set_hermes_memory,
            crate::commands::get_hermes_memory_limits,
            crate::commands::set_hermes_memory_enabled,
            // Global upstream proxy
            crate::commands::get_global_proxy_url,
            crate::commands::set_global_proxy_url,
            crate::commands::test_proxy_url,
            crate::commands::get_upstream_proxy_status,
            crate::commands::scan_local_proxies,
            // Window theme control
            crate::commands::set_window_theme,
            // Generic managed auth commands
            crate::commands::auth_start_login,
            crate::commands::auth_poll_for_account,
            crate::commands::auth_list_accounts,
            crate::commands::auth_get_status,
            crate::commands::auth_remove_account,
            crate::commands::auth_set_default_account,
            crate::commands::auth_logout,
            // Copilot OAuth commands (multi-account support)
            crate::commands::copilot_start_device_flow,
            crate::commands::copilot_poll_for_auth,
            crate::commands::copilot_poll_for_account,
            crate::commands::copilot_list_accounts,
            crate::commands::copilot_remove_account,
            crate::commands::copilot_set_default_account,
            crate::commands::copilot_get_auth_status,
            crate::commands::copilot_logout,
            crate::commands::copilot_is_authenticated,
            crate::commands::copilot_get_token,
            crate::commands::copilot_get_token_for_account,
            crate::commands::copilot_get_models,
            crate::commands::copilot_get_models_for_account,
            crate::commands::copilot_get_usage,
            crate::commands::copilot_get_usage_for_account,
            // OMO commands
            crate::commands::read_omo_local_file,
            crate::commands::get_current_omo_provider_id,
            crate::commands::disable_current_omo,
            crate::commands::read_omo_slim_local_file,
            crate::commands::get_current_omo_slim_provider_id,
            crate::commands::disable_current_omo_slim,
            // Workspace files (OpenClaw)
            crate::commands::read_workspace_file,
            crate::commands::write_workspace_file,
            // Daily memory files (OpenClaw workspace)
            crate::commands::list_daily_memory_files,
            crate::commands::read_daily_memory_file,
            crate::commands::write_daily_memory_file,
            crate::commands::delete_daily_memory_file,
            crate::commands::search_daily_memory_files,
            crate::commands::open_workspace_directory,
            // lightweight mode (for testing or low-resource environments)
            crate::commands::enter_lightweight_mode,
            crate::commands::exit_lightweight_mode,
            crate::commands::is_lightweight_mode,
        ]
    };
}
